DROP TABLE IF EXISTS issues;

CREATE TABLE issues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  type TEXT NOT NULL,
  details TEXT NOT NULL,
  screenshot TEXT,
  status TEXT NOT NULL DEFAULT 'Open',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
